import secrets
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext as _
from base.models import BaseModel

User = get_user_model()


class ApiKey(BaseModel):
    """
    API Keys that can be generated by SYSTEMADMIN ,'is_superuser': Trueusers.
    These keys allow external systems to access resources.
    """
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='api_keys',
        limit_choices_to={'role': 'SYSTEMADMIN', 'is_superuser': True}
    )
    name = models.CharField(
        max_length=255,
        help_text="Descriptive name for this API key (e.g., 'Mobile App', 'External Service')"
    )
    key = models.CharField(
        max_length=128,
        unique=True,
        editable=False,
        help_text="The actual API key"
    )
    prefix = models.CharField(
        max_length=8,
        editable=False,
        help_text="First 8 characters of the key for identification"
    )
    is_active = models.BooleanField(
        default=True,
        help_text="Whether this API key is active and can be used"
    )
    expires_at = models.DateTimeField(
        blank=True,
        null=True,
        help_text="When this API key expires (optional)"
    )
    last_used_at = models.DateTimeField(
        blank=True,
        null=True,
        help_text="Last time this API key was used"
    )

    slug = None
    metadata = None

    class Meta:
        ordering = ("-created_at",)
        verbose_name = _("API Key")
        verbose_name_plural = _("API Keys")
        indexes = [
            models.Index(fields=['key']),
            models.Index(fields=['prefix']),
            models.Index(fields=['is_active', '-created_at']),
        ]

    def __str__(self):
        return f"{self.name} ({self.prefix}...)"

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = self.generate_key()
            self.prefix = self.key[:8]
        super().save(*args, **kwargs)

    @staticmethod
    def generate_key():
        """Generate a secure random API key"""
        return f"pemost_{secrets.token_urlsafe(40)}"

    def is_valid(self):
        """Check if the API key is valid (active and not expired)"""
        from django.utils import timezone
        if not self.is_active:
            return False
        if self.expires_at and self.expires_at < timezone.now():
            return False
        return True

    def record_usage(self):
        """Record that this API key was just used"""
        from django.utils import timezone
        self.last_used_at = timezone.now()
        self.save(update_fields=['last_used_at'])
