services:
  database_v2:
    image: postgis/postgis:15-3.4-alpine
    container_name: pemost_db_v2
    expose:
      - 5434
    env_file:
      - ./backend/environments/env.v2
    restart: unless-stopped
    volumes:
      - database_volume_v2:/var/lib/postgresql/data
    networks:
      - pemost_backend_pemost_prod_network

  backend_v2:
    image: gitjulia/pemost-backend
    container_name: pemost_backend_v2
    command: gunicorn project.wsgi:application --workers 16 --timeout 1500 --worker-class gevent --bind 0.0.0.0:8001
    restart: unless-stopped
    volumes:
      - migration_files_v2:/pemostbackend/migration_files:rw
      - static_volume_v2:/pemostbackend/static:rw
      - media_volume_v2:/pemostbackend/media:rw
    expose:
      - 8001
    env_file:
      - ./backend/environments/env.v2
    networks:
      - pemost_backend_pemost_prod_network
    depends_on:
      - database_v2
      - redis_v2

  # sockets_v2:
  #   image: gitjulia/pemost-backend
  #   container_name: pemost_sockets_v2
  #   command: daphne --bind 0.0.0.0 --port 6657 --verbosity 0 project.asgi:application
  #   restart: unless-stopped
  #   volumes:
  #     - migration_files_v2:/pemostbackend/migration_files:rw
  #     - static_volume_v2:/pemostbackend/static:rw
  #     - media_volume_v2:/pemostbackend/media:rw
  #   networks:
  #     - pemost_backend_pemost_prod_network
  #   ports:
  #     - 6657:6657
  #   depends_on:
  #     - backend_v2
  #     - redis_v2
  #     - database_v2
  #   env_file:
  #     - ./backend/environments/env.v2

  redis_v2:
    image: redis:latest
    container_name: pemost_redis_v2
    restart: unless-stopped
    command: ["redis-server", "--port", "6380"]
    expose:
      - 6380
    networks:
      - pemost_backend_pemost_prod_network

  celery_worker_v2:
    image: gitjulia/pemost-backend
    container_name: pemost_celery_worker_v2
    restart: unless-stopped
    env_file:
      - ./backend/environments/env.v2
    command: celery -A project worker -l info
    volumes:
      - migration_files_v2:/pemostbackend/migration_files:rw
      - static_volume_v2:/pemostbackend/static:rw
      - media_volume_v2:/pemostbackend/media:rw
    networks:
      - pemost_backend_pemost_prod_network
    depends_on:
      - backend_v2
      - redis_v2
      - database_v2

  celery_beat_v2:
    image: gitjulia/pemost-backend
    container_name: pemost_celery_beat_v2
    restart: unless-stopped
    env_file:
      - ./backend/environments/env.v2
    command: celery -A project beat -l info
    volumes:
      - migration_files_v2:/pemostbackend/migration_files:rw
      - static_volume_v2:/pemostbackend/static:rw
      - media_volume_v2:/pemostbackend/media:rw
    networks:
      - pemost_backend_pemost_prod_network
    depends_on:
      - backend_v2
      - redis_v2
      - database_v2

networks:
  pemost_backend_pemost_prod_network:
    external: true

volumes:
  static_volume_v2:
  media_volume_v2:
  database_volume_v2:
  celery_worker_volume_v2:
  celery_beat_v2_volume:
  migration_files_v2:
